# Use an official lightweight Python image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . .

# Expose the port if your application needs one (e.g., for a web server)
EXPOSE 8000

# Set the command to run your Python application
CMD ["fastapi", "run", "main.py"]
